version: '3.4'

services:
  webapplication1:
    image: ${DOCKER_REGISTRY-}webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    depends_on:
      - mongoDB
  mongoDB:
    image: mongo
    restart: always
    volumes:
      - /data:/data/db
    ports:
      - 27017:27017
